### ISSUE TITLE
Support for KeQueryMaximumProcessorCountEx equivalent

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/usersim#137]

**Comment by nibanks** [comment]
MsQuic:

- [Windows user mode](https://github.com/microsoft/msquic/blob/main/src/inc/quic_platform_winuser.h#L993)
- [Windows kernel mode](https://github.com/microsoft/msquic/blob/main/src/inc/quic_platform_winkernel.h#L884)
- [Posix](https://github.com/microsoft/msquic/blob/main/src/inc/quic_platform_posix.h#L1294)
