### ISSUE TITLE
Support for ebpf_get_current_cpu equivalent in cxplat

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/usersim#138]

**Comment by nibanks** [comment]
See https://github.com/microsoft/usersim/issues/137 for links for how MsQuic does it.

**Comment by dthaler** [comment]
Windows KM: KeGetCurrentProcessorNumberEx(NULL)
Windows UM: https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocessornumber
