### ISSUE TITLE
The use of Directory.Build.Props breaks consuming modules attempting to do ASAN builds

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/usersim#151]
This file [Directory.Build.props](https://github.com/microsoft/usersim/blob/main/Directory.Build.props) overrides all the settings from the any Directory.Build.props higher in the directory hierarchy. 

eBPF-For-Windows has its own "Directory.Build.props" file that controls address sanitizer options, but setting this in submodule overrides this. 

The result is that the consuming module is build with ASAN, but this project is not.

@dthaler You added the Directory.Build.props to this project. Do you have any suggestions on how to resolve this?

**Comment by dthaler** [comment]
Here's what Bing chat suggests:

You can conditionally import the `Directory.Build.props` file based on a property that you define in your outer repository’s `Directory.Build.props` file. Here’s how you can do it:

In your outer repository’s `Directory.Build.props` file, define a property to indicate that the build is happening in the context of the outer repository. For example:
XML
AI-generated code. Review and use carefully. [More info on FAQ](https://www.bing.com/new#faq).

```
<Project>
  <PropertyGroup>
    <OuterBuild>true</OuterBuild>
  </PropertyGroup>
</Project>
```
In your inner repository’s `Directory.Build.props` file, conditionally import the settings based on the `OuterBuild` property. For example:
XML
AI-generated code. Review and use carefully. [More info on FAQ](https://www.bing.com/new#faq).
```
<Project>
  <Import Project="Settings.props" Condition="'$(OuterBuild)' != 'true'" />
</Project>
```
In this example, `Settings.props` would contain the settings that are currently in your inner repository’s `Directory.Build.props` file. These settings will only be imported if the `OuterBuild` property is not set to true, which would be the case when building from the outer repository.

Remember to adjust the paths and filenames according to your project structure. This approach allows you to control the import of settings based on the build context. Hope this helps! 😊

**Comment by Alan-Jowett** [comment]
Not sure I follow how this would work. The inner Directory.Build.props will prevent the outer one from being loaded at all.
