### ISSUE TITLE
Potential issues with dispatch IRQL emulation

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/usersim#42]
From code review, I spotted two potential issues with usersim's emulation of code running at dispatch IRQL:

1. Two separate usersim threads of execution at dispatch level on the same processor can be interleaved by the OS dispatcher. This is prohibited in kernel dispatch level code, by definition.
2. A usersim thread running at dispatch level can be preempted by another thread of execution running at lower IRQL due to various priority boosting strategies (e.g., IO completion, anti-priority-inversion, etc.) in Windows. It appears that code running at a realtime priority is immune to dispatcher boosts.

**Comment by dthaler** [comment]
> 1. Two separate usersim threads of execution at dispatch level on the same processor can be interleaved by the OS dispatcher. This is prohibited in kernel dispatch level code, by definition.

https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/always-preemptible-and-always-interruptible says: "Some threads have real-time priority attributes: these time-critical threads run to completion unless they are preempted by a thread that has a higher real-time priority attribute."

Thus, two threads at dispatch level using THREAD_PRIORITY_TIME_CRITICAL should not be interleaved.

> 2. A usersim thread running at dispatch level can be preempted by another thread of execution running at lower IRQL due to various priority boosting strategies (e.g., IO completion, anti-priority-inversion, etc.) in Windows. It appears that code running at a realtime priority is immune to dispatcher boosts.

There is a current bug (which I will use this issue to address) that pseudo-DPCs correctly run at THREAD_PRIORITY_TIME_CRITICAL, but DISPATCH_LEVEL used with KeRaiseIrql is incorrectly mapped to THREAD_PRIORITY_HIGHEST instead of THREAD_PRIORITY_TIME_CRITICAL.  Thanks for catching this.

**Comment by mtfriesen** [comment]
Wow, that's the first I heard about threads not being preemptible by other threads of the same priority! I'm not sure that documentation implies THREAD_PRIORITY_TIME_CRITICAL has the real time priority attribute.

A litmus test shows main() being preempted by another thread. I also set the process priority to real-time, which still doesn't seem to do the trick. Thoughts?

```
#include <windows.h>
#include <stdio.h>

#define VERIFY(e) ((e) ? TRUE : (fprintf(stderr, #e " failed\n"), exit(1), FALSE))

DWORD
WINAPI
ThreadRoutine(
    VOID *ThreadParameter
    )
{
    UNREFERENCED_PARAMETER(ThreadParameter);

    VERIFY(SetPriorityClass(GetCurrentProcess(), REALTIME_PRIORITY_CLASS));
    VERIFY(SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL));
    VERIFY(SetThreadAffinityMask(GetCurrentThread(), 1));

    printf("Preempted main!\n");
}

int
main(
    int argc,
    char *argv[]
    )
{
    VERIFY(SetPriorityClass(GetCurrentProcess(), REALTIME_PRIORITY_CLASS));
    VERIFY(SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL));
    VERIFY(SetThreadAffinityMask(GetCurrentThread(), 1));

    VERIFY(CreateThread(NULL, 0, ThreadRoutine, NULL, 0, NULL));

    while (TRUE);
}
```

Separately, I'm still not sure the usersim dispatch level code properly affinitizes itself to the current logical processor, which allows DPCs and unaffinitized dispatch level code to share a logical processor.

**Comment by mtfriesen** [comment]
So concretely, I believe the fix needs to be to set the process priority class to realtime during initialization (to prevent priority boosts of non-dispatch threads to dispatch level), _then_ set the thread priority to a higher value when raising IRQL, and _then_ either acquire a per-logical-processor critical section or set a hard thread affinity, depending on the CPU emulation model.

**Comment by mtfriesen** [comment]
@dthaler I do not have access to reactivate this issue to track the fix. Could you reactivate it or grant contributor access to me?

**Comment by dthaler** [comment]
@mtfriesen Done.  Also feel free to submit a PR if you think you know the best fix. :)
